# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MERN Mom
email: chazona@chazonabaum.com
description: > # this means to ignore newlines until "baseurl:"
  When you're a mom in a male-dominated industry, it can sometimes be hard to 
  have someone in your corner or who understands your challenges. I had my 
  kids before learning to code, and I started my tech career while they were 
  still pre-school age. I've literally led code meetups with my toddler around 
  my ankles. While our experience may not be identical, I've got your back on 
  this JavaScript journey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:slug.html
twitter_username: chznbaum
github_username:  chznbaum

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
