# Site Settings
baseurl: 		""
title: 			MERN Mom

name: 			MERN Mom
description: 	Life, Kids, and JavaScript
url: 			"http://mernmom.com"

paginate: 		5
paginate_path: 	"blog/page:num"

twitter: 		chznbaum
email: 			chazona@chazonabaum.com

disqus: 		mernmom
analytics: 		UA-86554564-1

copyright: 		Copyright 2017 <a href="http://chazonabaum.com">Chazona Baum</a>.	

# Build Settings
permalinks: 	pretty

gems:		[jekyll-paginate]
